Update aeson to greater than 2
pjones/themoviedb pull request #10
Opened 2022-07-06 17:05 UTC by ragreener1

aeson >=2 Introduced the Data.Aeson.Key.Key type and replaced any Text keys with Key.

Builds & tests ok

2022-07-06 17:05 UTC, ragreener1 commented
Closes #9 

If ok would you release to hackage please!

2022-07-06 20:25 UTC, pjones commented
I will definitely get this out to hackage as soon as this is merged.

2022-07-07 17:05 UTC, pjones requested changes

2022-07-07 17:05 UTC, pjones commented on src/Network/API/TheMovieDB/Internal/Settings.hs
> +    tmdbKey :: Network.API.TheMovieDB.Internal.Types.Key,
@ragreener1 Can you explain why this change was needed.  Thank you.

2022-07-07 17:05 UTC, pjones commented on src/Network/API/TheMovieDB/Internal/Settings.hs
> +defaultSettings :: Network.API.TheMovieDB.Internal.Types.Key -> Settings
Same as above.

2022-07-07 20:04 UTC, ragreener1 commented on src/Network/API/TheMovieDB/Internal/Settings.hs
> +    tmdbKey :: Network.API.TheMovieDB.Internal.Types.Key,
Sure. The new version of Aesop introduces a Key type. This clashes with your key type, so we need to be explicit

2022-07-07 23:52 UTC, pjones commented
@ragreener1 Can you enable "allow maintainers to add commits" so I can clean up imports and them merge?  Thank you.

2022-07-12 21:56 UTC, merged